allow_remote_control yes
listen_on unix:/tmp/mykitty

font_family JetBrainsMono Nerd Font Mono

font_size 14
window_margin_width 1
window_padding_width 1
hide_window_decorations titlebar-only

cursor_trail 10
cursor_trail_start_threshold 0
cursor_trail_decay 0.01 0.05

inactive_border_color #444
inactive_text_alpha 0.5

# Mapping
enabled_layouts splits,stack

map cmd+- launch --location=hsplit --cwd=current
map cmd+\ launch --location=vsplit --cwd=current

#map cmd+h neighboring_window left
#map cmd+l neighboring_window right
#map cmd+k neighboring_window up
#map cmd+j neighboring_window down
map cmd+z toggle_layout stack
map cmd+j kitten pass_keys.py bottom cmd+j
map cmd+k kitten pass_keys.py top    cmd+k
map cmd+h kitten pass_keys.py left   cmd+h
map cmd+l kitten pass_keys.py right  cmd+l

map cmd+shift+h move_window left
map cmd+shift+l move_window right
map cmd+shift+k move_window up
map cmd+shift+j move_window down

map cmd+shift+r layout_action rotate

map cmd+shift+left resize_window narrower
map cmd+shift+right resize_window wider
map cmd+shift+up resize_window taller
map cmd+shift+down resize_window shorter 3
map cmd+= resize_window reset

map cmd+shift+plus change_font_size current +1.0
map cmd+shift+minus change_font_size current -1.0
map cmd+0 change_font_size all 0

map ctrl+a>f focus_visible_window
visual_window_select_characters 1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ

map cmd+w close_window
map ctrl+a>x close_tab

tab_title_template "{bell_symbol}{activity_symbol}{'  ' if layout_name == 'stack' and num_windows > 1 else ''}{fmt.fg.tab}{index}. {title}"

map cmd+] next_tab
map cmd+[ previous_tab

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# BEGIN_KITTY_THEME
include Monokai.conf
# END_KITTY_THEME

shell_integration enabled

map ctrl+a>s combine : save_as_session --save-only --use-foreground-process .  : launch --type=overlay sh -c 'echo "kitty session saved."; echo; read -r -p "Press Enter to exit"; echo ""'

map ctrl+a>shift+e launch --type=tab nvim ~/.config/kitty/kitty.conf

#: Reload kitty.conf
map ctrl+a>shift+r combine : load_config_file : launch --type=overlay sh -c 'echo "kitty config reloaded."; echo; read -r -p "Press Enter to exit"; echo ""'

#: Debug kitty configuration
map ctrl+a>shift+d     debug_config

